-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','김치','식용유','국')
    GROUP BY CATEGORY
) FP2
ON FP.CATEGORY = FP2.CATEGORY AND FP.PRICE = FP2.MAX_PRICE
ORDER BY PRICE DESC