-- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, P.PRICE *  COUNT(OS.SALES_AMOUNT) AS 'SALES'
# FROM PRODUCT P INNER JOIN OFFLINE_SALE OS
# ON P.PRODUCT_ID = OS.PRODUCT_ID
# GROUP BY OS.PRODUCT_ID
# ORDER BY SALES DESC, P.PRODUCT_CODE

SELECT P.PRODUCT_CODE, sum(OS.SALES_AMOUNT * P.PRICE) AS 'SALES'
FROM OFFLINE_SALE OS INNER JOIN PRODUCT P
ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE